import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const icons = JSON.parse(readFileSync(join(root, "src/icons.json"), "utf8"));
const loader = readFileSync(join(root, "src/loader.js"), "utf8");

for (const [name, path] of Object.entries(icons)) {
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(name)) throw new Error(`Invalid icon name: ${name}`);
  if (typeof path !== "string" || !path.trim()) throw new Error(`Empty path: ${name}`);
}

const body = Object.entries(icons)
  .map(([n, p]) => `  ${JSON.stringify(n)}:\n    ${JSON.stringify(p)}`)
  .join(",\n\n");

const out =
  `// Generated by scripts/build.mjs - do not edit; edit src/ instead.\n` +
  `const LEONS_ICONS_MAP = {\n\n${body}\n};\n\n` +
  loader.replaceAll("__VERSION__", version);

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist/leons-ha-icons.js"), out);
const readmePath = join(root, "README.md");
const marker = (tag, value) => [new RegExp(`(<!--${tag}-->)[^<]*(<!--/${tag}-->)`), `$1${value}$2`];
let readme = readFileSync(readmePath, "utf8");
for (const [tag, value] of [["count", Object.keys(icons).length]]) {
  const [re, rep] = marker(tag, value);
  if (!re.test(readme)) throw new Error(`README marker missing: ${tag}`);
  readme = readme.replace(re, rep);
}
writeFileSync(readmePath, readme);

console.log(`Built dist/leons-ha-icons.js (${Object.keys(icons).length} icons, v${version})`);
